server:
  port: 8087
  servlet:
    path: /
#控制日志的级别  key：value （包名：日志级别）
logging:
  level:
    com.andy: debug
    #org.springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/woniutrip
    username: root
    password: root

  #thymeleaf start
  thymeleaf:
    cache: false #关闭缓存，不然没办法看到实时页面
    #########################################################################################
    #mode: HTML5
    #实际项目中可能会有不太严格的html格式，此时设置的model=HTML5将会对非常严格的报错，可以参考一下配置
#    你可能会发现在默认配置下，thymeleaf对.html的内容要求很严格，比如<meta charset="UTF-8" />，
     #如果少最后的标签封闭符号/，就会报错而转到错误页。也比如你在使用Vue.js这样的库，然后有<div v-cloak></div>这样的html代码，
     #也会被thymeleaf认为不符合要求而抛出错误。
     #
     #因此，建议增加下面这段：
     #
     #spring.thymeleaf.mode = LEGACYHTML5
     #spring.thymeleaf.mode的默认值是HTML5，其实是一个很严格的检查，改为LEGACYHTML5可以得到一个可能更友好亲切的格式要求。
#     需要注意的是，LEGACYHTML5需要搭配一个额外的库NekoHTML才可用。
      #<dependency>
      #       <groupId>net.sourceforge.nekohtml</groupId>
      #       <artifactId>nekohtml</artifactId>
      #       <version>1.9.22</version>
      #</dependency>
#     #####################################################################################################
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  # thymeleaf end
mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  引用了通用mapper之后会自动开启驼峰转换，不需要再自己配置
  type-aliases-package: com.andy.model
  #mapper-locations: mapper/*.xml